### PR TITLE
Implement the suggestion from the issue #138

### PR DESCRIPTION
**Pull request by xspager**
This might not be the best solution but is enough to implement the functionality asked by the issue #138 .

### CODE REVIEW

**Comment by brandonhellman** [comment]
Can you also use the other two values from this array https://github.com/Kadauchi/mturk-suite/blob/f935df415a4884443d8066a4524e0f3709364770/background/hit-exporter.js#L140-L144 so it can match Categorization and Photo Masters too.

**Comment by xspager** [comment]
Do they need each a option or the two fall into the "Master" category? I'm not sure how best implement this without repeating the the code right now, do you have a suggestion?

**Comment by brandonhellman** [comment]
Making them all fall under a single Master's category should be fine. Photo/Cat Masters HITs are rare enough where its not worth it to include separate options for them imo.

**Comment by xspager** [comment]
Ok, good 👍

**Pull request merged**
